# Generated by Django 4.2.10 on 2024-02-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="image",
            field=models.ImageField(upload_to="marca_imgs/"),
        ),
    ]
